/**
 * Brainrex API Explorer
 * Welcome to the Brainrex API explorer, we make analytics tools for crypto and blockchain. Our currently propiertary models offer sentiment analysis, market making, blockchain monitoring and face-id verification. This AI models can be consumed from this API. We also offer integrations to open data and propietary data providers, as well as free test data we collect. There is a collection of data transformation tools. Join our Telegram group to get the latest news and ask questions [https://t.me/brainrex, #brainrex](https://t.me/brainrex). More about Brainrex at [https://brainrex.com](http://brainrex.com). Full Documentation can be found at [https://brainrexapi.github.io/docs](https://brainrexapi.github.io/docs)
 *
 * OpenAPI spec version: 0.1.1
 * Contact: support@brainrex.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import java.util.Date

case class InlineResponse201 (
  // Start date in YYYY/MM/DD
  startDate: Option[Date] = None,
  // End date in YYYY/MM/DD
  endDate: Option[Date] = None,
  // Opening price quote of the time frame with two decimal points
  open: Option[Float] = None,
  // Closing price quote of the time frame with two decimal points
  close: Option[Float] = None,
  // Highest price of the time frame with two decimal points
  high: Option[Float] = None,
  // Volume of currency exchanged in the time frame with two decimal points
  vol: Option[Float] = None
)

