/**
 * Brainrex API Explorer
 * Welcome to the Brainrex API explorer, we make analytics tools for crypto and blockchain. Our currently propiertary models offer sentiment analysis, market making, blockchain monitoring and face-id verification. This AI models can be consumed from this API. We also offer integrations to open data and propietary data providers, as well as free test data we collect. There is a collection of data transformation tools. Join our Telegram group to get the latest news and ask questions [https://t.me/brainrex, #brainrex](https://t.me/brainrex). More about Brainrex at [https://brainrex.com](http://brainrex.com). Full Documentation can be found at [https://brainrexapi.github.io/docs](https://brainrexapi.github.io/docs)
 *
 * OpenAPI spec version: 0.1.1
 * Contact: support@brainrex.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api

import java.text.SimpleDateFormat

import io.swagger.client.model.InlineResponse201
import io.swagger.client.model.Request
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class BlockchainApi(
  val defBasePath: String = "https://brainrexapi.appspot.com:5000/api",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new BlockchainApiAsyncHelper(client, config)

  /**
   * Calculate average transccion fee of a given blockchain
   * Calculates the average trasnsaction fee of a given 
   *
   * @param request Name of the blockchain and date range. 
   * @return InlineResponse201
   */
  def blockchainAverageTx(request: Request): Option[InlineResponse201] = {
    val await = Try(Await.result(blockchainAverageTxAsync(request), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Calculate average transccion fee of a given blockchain asynchronously
   * Calculates the average trasnsaction fee of a given 
   *
   * @param request Name of the blockchain and date range. 
   * @return Future(InlineResponse201)
   */
  def blockchainAverageTxAsync(request: Request): Future[InlineResponse201] = {
      helper.blockchainAverageTx(request)
  }

  /**
   * The blockchains data structure supported by the Brainrex API
   * List of supported blockchains networks for analysis. The full history of the networks are available.
   *
   * @return List[Any]
   */
  def blockchainList(): Option[List[Any]] = {
    val await = Try(Await.result(blockchainListAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * The blockchains data structure supported by the Brainrex API asynchronously
   * List of supported blockchains networks for analysis. The full history of the networks are available.
   *
   * @return Future(List[Any])
   */
  def blockchainListAsync(): Future[List[Any]] = {
      helper.blockchainList()
  }

}

class BlockchainApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def blockchainAverageTx(request: Request)(implicit reader: ClientResponseReader[InlineResponse201], writer: RequestWriter[Request]): Future[InlineResponse201] = {
    // create path and map variables
    val path = (addFmt("/average_tx_fee"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (request == null) throw new Exception("Missing required parameter 'request' when calling BlockchainApi->blockchainAverageTx")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(request))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def blockchainList()(implicit reader: ClientResponseReader[List[Any]]): Future[List[Any]] = {
    // create path and map variables
    val path = (addFmt("/list_blockchain"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
