/**
 * Brainrex API Explorer
 * Welcome to the Brainrex API explorer, we make analytics tools for crypto and blockchain. Our currently propiertary models offer sentiment analysis, market making, blockchain monitoring and face-id verification. This AI models can be consumed from this API. We also offer integrations to open data and propietary data providers, as well as free test data we collect. There is a collection of data transformation tools. Join our Telegram group to get the latest news and ask questions [https://t.me/brainrex, #brainrex](https://t.me/brainrex). More about Brainrex at [https://brainrex.com](http://brainrex.com). Full Documentation can be found at [https://brainrexapi.github.io/docs](https://brainrexapi.github.io/docs)
 *
 * OpenAPI spec version: 0.1.1
 * Contact: support@brainrex.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api

import java.text.SimpleDateFormat

import io.swagger.client.model.InlineResponse201
import io.swagger.client.model.InlineResponse2011
import io.swagger.client.model.Request1
import io.swagger.client.model.Request2
import io.swagger.client.model.Request3
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class CryptoApi(
  val defBasePath: String = "https://brainrexapi.appspot.com:5000/api",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new CryptoApiAsyncHelper(client, config)

  /**
   * Downloads candle format market data
   * Returns a list of candle data from specified market and data range
   *
   * @param request Person to create 
   * @return InlineResponse201
   */
  def exchangesDownloadCandles(request: Request2): Option[InlineResponse201] = {
    val await = Try(Await.result(exchangesDownloadCandlesAsync(request), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Downloads candle format market data asynchronously
   * Returns a list of candle data from specified market and data range
   *
   * @param request Person to create 
   * @return Future(InlineResponse201)
   */
  def exchangesDownloadCandlesAsync(request: Request2): Future[InlineResponse201] = {
      helper.exchangesDownloadCandles(request)
  }

  /**
   * The markets data structure supported by the Brainrex Market API
   * Read the list of supported markets ( currency pairs ) in each exchange
   *
   * @return List[Any]
   */
  def exchangesList(): Option[List[Any]] = {
    val await = Try(Await.result(exchangesListAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * The markets data structure supported by the Brainrex Market API asynchronously
   * Read the list of supported markets ( currency pairs ) in each exchange
   *
   * @return Future(List[Any])
   */
  def exchangesListAsync(): Future[List[Any]] = {
      helper.exchangesList()
  }

  /**
   * Market Making as a Service API.
   * Our AI will trade at the risk level you want, you need to provide your credential to the exchange you are trading at.
   *
   * @param request Name of exchange and currency pair you want to provide liquidity 
   * @return InlineResponse2011
   */
  def exchangesMarketmaker(request: Request3): Option[InlineResponse2011] = {
    val await = Try(Await.result(exchangesMarketmakerAsync(request), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Market Making as a Service API. asynchronously
   * Our AI will trade at the risk level you want, you need to provide your credential to the exchange you are trading at.
   *
   * @param request Name of exchange and currency pair you want to provide liquidity 
   * @return Future(InlineResponse2011)
   */
  def exchangesMarketmakerAsync(request: Request3): Future[InlineResponse2011] = {
      helper.exchangesMarketmaker(request)
  }

  /**
   * The exchanges data structure supported by the Brainrex API
   * Read the list of supported exchanges in the Market Data API
   *
   * @return List[Any]
   */
  def exchangesRead(): Option[List[Any]] = {
    val await = Try(Await.result(exchangesReadAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * The exchanges data structure supported by the Brainrex API asynchronously
   * Read the list of supported exchanges in the Market Data API
   *
   * @return Future(List[Any])
   */
  def exchangesReadAsync(): Future[List[Any]] = {
      helper.exchangesRead()
  }

  /**
   * Download raw ticker data from major crypto markets
   * Downloads specified asset class and market and time frame. Of our raw ticker data format
   *
   * @param request Person to create 
   * @return InlineResponse201
   */
  def exchangesTickerDataDownload(request: Request1): Option[InlineResponse201] = {
    val await = Try(Await.result(exchangesTickerDataDownloadAsync(request), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Download raw ticker data from major crypto markets asynchronously
   * Downloads specified asset class and market and time frame. Of our raw ticker data format
   *
   * @param request Person to create 
   * @return Future(InlineResponse201)
   */
  def exchangesTickerDataDownloadAsync(request: Request1): Future[InlineResponse201] = {
      helper.exchangesTickerDataDownload(request)
  }

}

class CryptoApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def exchangesDownloadCandles(request: Request2)(implicit reader: ClientResponseReader[InlineResponse201], writer: RequestWriter[Request2]): Future[InlineResponse201] = {
    // create path and map variables
    val path = (addFmt("/download_candles"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (request == null) throw new Exception("Missing required parameter 'request' when calling CryptoApi->exchangesDownloadCandles")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(request))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def exchangesList()(implicit reader: ClientResponseReader[List[Any]]): Future[List[Any]] = {
    // create path and map variables
    val path = (addFmt("/markets"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def exchangesMarketmaker(request: Request3)(implicit reader: ClientResponseReader[InlineResponse2011], writer: RequestWriter[Request3]): Future[InlineResponse2011] = {
    // create path and map variables
    val path = (addFmt("/market_making"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (request == null) throw new Exception("Missing required parameter 'request' when calling CryptoApi->exchangesMarketmaker")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(request))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def exchangesRead()(implicit reader: ClientResponseReader[List[Any]]): Future[List[Any]] = {
    // create path and map variables
    val path = (addFmt("/exchanges"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def exchangesTickerDataDownload(request: Request1)(implicit reader: ClientResponseReader[InlineResponse201], writer: RequestWriter[Request1]): Future[InlineResponse201] = {
    // create path and map variables
    val path = (addFmt("/download_ticker"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (request == null) throw new Exception("Missing required parameter 'request' when calling CryptoApi->exchangesTickerDataDownload")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(request))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
